[2023-12-10 16:02:19,610][__main__][INFO] - For logs, checkpoints and samples check /Volumes/Castile/HackerProj/denoiser
[2023-12-10 16:02:22,130][__main__][ERROR] - Some error happened
Traceback (most recent call last):
  File "/Volumes/Castile/HackerProj/denoiser/train.py", line 121, in main
    _main(args)
  File "/Volumes/Castile/HackerProj/denoiser/train.py", line 114, in _main
    run(args)
  File "/Volumes/Castile/HackerProj/denoiser/train.py", line 41, in run
    model = ConvTasNet(sources={'clean': clean_files, 'noisy': noise_files}, N=128, L=20, B=128, H=512, P=3, X=8, R=4,audio_channels=2, norm_type="gLN", causal=False, mask_nonlinear='relu', sample_rate=16000, segment_length=44100 * 2 * 40) # frame_length=400, frame_step=10 创建模型实例，并使用args参数初始化模型
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Castile/HackerProj/denoiser/denoiser/utils.py", line 29, in __init__
    init(self, *args, **kwargs)
  File "/Volumes/Castile/HackerProj/denoiser/denoiser/ConvTasNet.py", line 67, in __init__
    args, _, _, kwargs = inspect.getargvalues(inspect.currentframe())
                         ^^^^^^^
NameError: name 'inspect' is not defined
