[2023-12-06 17:20:24,498][__main__][INFO] - For logs, checkpoints and samples check /Volumes/Castile/HackerProj/denoiser
[2023-12-06 17:20:26,958][__main__][ERROR] - Some error happened
Traceback (most recent call last):
  File "/Volumes/Castile/HackerProj/denoiser/train.py", line 123, in main
    _main(args)
  File "/Volumes/Castile/HackerProj/denoiser/train.py", line 116, in _main
    run(args)
  File "/Volumes/Castile/HackerProj/denoiser/train.py", line 41, in run
    model = ConvTasNet(sources={'clean': clean_files, 'noisy': noise_files}, N=128, L=20, B=128, H=512, P=3, X=8, R=4,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Castile/HackerProj/denoiser/denoiser/ConvTasnet1.py", line 50, in __init__
    self.separator = TemporalConvNet(N, B, H, P, X, R)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Castile/HackerProj/denoiser/denoiser/ConvTasnet1.py", line 82, in __init__
    layers += [TemporalBlock(N, H, P, kernel_size, dilation)]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Castile/HackerProj/denoiser/denoiser/ConvTasnet1.py", line 93, in __init__
    self.conv1 = nn.Conv1d([20, 128, 128], weight, in_channels, out_channels, kernel_size, bias=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Toys/Factory/anaconda3/envs/dnoise/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 297, in __init__
    super().__init__(
  File "/Volumes/Toys/Factory/anaconda3/envs/dnoise/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 88, in __init__
    if in_channels % groups != 0:
       ~~~~~~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for %: 'list' and 'int'
